import Sidebar from "@/components/shared/Sidebar";

export const metadata = {
  title: "Nextjs Dashboard",
  description: "Generated by create next app",
};
const DashBoardLayout = ({ children }) => {
  return (
    <div>
      <Sidebar />
      {children}
    </div>
  );
};

export default DashBoardLayout;
